/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.cliente;

import controlador.ControladorCine;
import modelo.Cliente;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Usuario
 */
public class ClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClienteFrame
     */
    
    private final ControladorCine controlador;
    private final Cliente cliente;
    private String codigoSesionSeleccionada = null;
    private static final DateTimeFormatter FMT_FECHA = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    private static final DateTimeFormatter FMT_HORA  = DateTimeFormatter.ofPattern("HH:mm");
    
    public ClienteFrame(ControladorCine controlador, Cliente cliente) {
        this.controlador = controlador;
        this.cliente = cliente;
        initComponents();
        TextAbono.setEditable(false);
        TextAbono.setText(obtenerDescuentoPorAbono() + " %");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                volverALogin();
            }
        });
        
        configurarTablaCartelera();
        PanelReserva.setVisible(false);
        RealizarReserva.setEnabled(false);
        ConfirmarReserva.setEnabled(false);
        PrecioEstimado.setEditable(false);

        configurarEventosCartelera();
        cargarCartelera();

        cargarMiInformacion();
        configurarTablaMisReservas();
        cargarMisReservas();
        CancelarReserva.setEnabled(false);
        tablaMisReservas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                CancelarReserva.setEnabled(tablaMisReservas.getSelectedRow() != -1);
            }
        });
        setTitle("OCine - Cliente");
        setLocationRelativeTo(null);
    }
    
    private void volverALogin() {
        int resp = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Cerrar sesión y volver al login?",
                "Salir",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (resp != javax.swing.JOptionPane.YES_OPTION) return;

        controlador.logout();

        ui.Login login = new ui.Login(controlador);
        login.setVisible(true);

        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        RealizarReserva = new javax.swing.JButton();
        PanelReserva = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        PrecioEstimado = new javax.swing.JTextField();
        ConfirmarReserva = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TextAbono = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMisReservas = new javax.swing.JTable();
        CancelarReserva = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Datos Personales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("Mi Información", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Sesion", "Pelicula", "Genero", "Tipo", "Fecha", "Hora", "Sala", "Precio Base", "Recargo Proyeccion", "Precio Final", "Plazas Disponibles"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODAS", "DRAMA", "COMEDIA", "TERROR", "CIENCIA_FICCION", "ACCION", "ANIMACION", "DOCUMENTAL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Filtrar por género");

        RealizarReserva.setText("Realizar Reserva");
        RealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarReservaActionPerformed(evt);
            }
        });

        jLabel5.setText("Número de Entradas");

        jLabel6.setText("Extras");

        jCheckBox1.setText("Palomitas (3€)");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Bebida (2€)");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Combo (4€)");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio Estimado");

        PrecioEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioEstimadoActionPerformed(evt);
            }
        });

        ConfirmarReserva.setText("CONFIRMAR RESERVA");
        ConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarReservaActionPerformed(evt);
            }
        });

        jLabel8.setText("Descuento de Abono");

        javax.swing.GroupLayout PanelReservaLayout = new javax.swing.GroupLayout(PanelReserva);
        PanelReserva.setLayout(PanelReservaLayout);
        PanelReservaLayout.setHorizontalGroup(
            PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReservaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelReservaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextAbono))
                    .addGroup(PanelReservaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ConfirmarReserva)
                    .addGroup(PanelReservaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(PrecioEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox3))
                .addGap(112, 112, 112))
        );
        PanelReservaLayout.setVerticalGroup(
            PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReservaLayout.createSequentialGroup()
                .addGroup(PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReservaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jCheckBox1))
                    .addGroup(PanelReservaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelReservaLayout.createSequentialGroup()
                        .addGroup(PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(jLabel6)
                            .addComponent(PrecioEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox3)
                            .addComponent(jLabel8)
                            .addComponent(TextAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ConfirmarReserva)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(RealizarReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RealizarReserva)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(PanelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cartelera", jPanel2);

        tablaMisReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Reserva", "Codigo Sesion", "Pelicula", "Fecha Sesion", "Hora Sesion", "Sala", "Entradas", "Extras", "Precio Final", "Estado Reserva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMisReservas.setColumnSelectionAllowed(true);
        tablaMisReservas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaMisReservas);
        tablaMisReservas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        CancelarReserva.setText("Cancelar Reserva");
        CancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarReservaActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecciona una Reserva para pulsar el botón de Cancelar Reserva");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CancelarReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarReserva)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mis Reservas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        PanelReserva.setVisible(false);
        ConfirmarReserva.setEnabled(false);
        RealizarReserva.setEnabled(false);
        codigoSesionSeleccionada = null;
        cargarCartelera();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void RealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarReservaActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this, "Selecciona una sesión de la tabla.", "No hay selección",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        codigoSesionSeleccionada = jTable1.getValueAt(fila, 0).toString();
        modelo.Sesion sesion = controlador.buscarSesionPorCodigo(codigoSesionSeleccionada);

        if (sesion == null || !sesionEsReservable(sesion)) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "La sesión ya ha comenzado o ya ha finalizado.\nNo se puede reservar.",
                "Sesión no reservable",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            PanelReserva.setVisible(false);
            ConfirmarReserva.setEnabled(false);
            cargarCartelera();
            return;
        }
        
        
        // Preparar spinner: mínimo 1, máximo plazas disponibles
        int max = Math.max(1, sesion.getPlazasDisponibles());
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, max, 1));

        // Reset extras
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        
        PanelReserva.setVisible(true);
        ConfirmarReserva.setEnabled(true);

        actualizarPrecioEstimado();

    }//GEN-LAST:event_RealizarReservaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void ConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarReservaActionPerformed
        if (codigoSesionSeleccionada == null) {
            javax.swing.JOptionPane.showMessageDialog(
                this, "Selecciona una sesión primero.", "Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        modelo.Sesion sesion = controlador.buscarSesionPorCodigo(codigoSesionSeleccionada);
        if (sesion == null || !sesionEsReservable(sesion)) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "La sesión ya ha comenzado o ya ha finalizado.\nNo se puede reservar.",
                "Sesión no reservable",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            PanelReserva.setVisible(false);
            ConfirmarReserva.setEnabled(false);
            cargarCartelera();
            return;
        }

        int entradas = (int) jSpinner1.getValue();
        boolean palomitas = jCheckBox1.isSelected();
        boolean bebida = jCheckBox2.isSelected();
        boolean combo = jCheckBox3.isSelected();

        String codigoReserva = generarCodigoReserva();

        try {
            controlador.crearReserva(
                codigoReserva,
                cliente,
                codigoSesionSeleccionada,
                entradas,
                palomitas,
                bebida,
                combo
            );

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Reserva creada correctamente.\nCódigo: " + codigoReserva,
                "Reserva confirmada",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Refrescar todo
            PanelReserva.setVisible(false);
            ConfirmarReserva.setEnabled(false);
            cargarCartelera();
            cargarMisReservas();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "No se pudo crear la reserva",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_ConfirmarReservaActionPerformed

    private void CancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarReservaActionPerformed
        int fila = tablaMisReservas.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecciona una reserva de la tabla.",
                "No hay selección",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // La columna 0 es "Codigo Reserva"
        String codigoReserva = tablaMisReservas.getValueAt(fila, 0).toString();

        modelo.Reserva reserva = controlador.buscarReservaPorCodigo(codigoReserva);
        if (reserva == null) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "La reserva ya no existe.",
                "No se pudo cancelar",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            cargarMisReservas();
            return;
        }

        modelo.Sesion sesion = reserva.getSesion();

        // Si ya terminó la película
        if (sesionHaFinalizado(sesion)) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "La película ya ha acabado.\nNo se puede cancelar la reserva.",
                "No se pudo cancelar",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // (Opcional) si está en curso
        if (sesionEstaEnCurso(sesion)) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "La película ya ha comenzado.\nNo se puede cancelar la reserva.",
                "No se pudo cancelar",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que quieres cancelar la reserva " + codigoReserva + "?\n" +
            "Recuerda: solo se puede cancelar hasta 2 horas antes de la sesión.",
            "Confirmar cancelación",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        try {
            controlador.cancelarReserva(codigoReserva);

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Reserva cancelada correctamente.",
                "Cancelación",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Refrescar tabla
            cargarMisReservas();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "No se pudo cancelar",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }        
    }//GEN-LAST:event_CancelarReservaActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void PrecioEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioEstimadoActionPerformed

    private void cargarMiInformacion() {
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);

        // Ajusta estos getters a los que tenga tu clase Cliente
        String nombre = cliente.getNombreCompleto();
        String dni = cliente.getDni();
        String email = cliente.getEmail();
        String telefono = cliente.getTelefono(); // si existe
        String abono = cliente.getTipoAbono().toString(); // devuelve "Básico", "Premium", "VIP"

        int descuento = obtenerDescuentoPorAbono(); // lo definimos abajo
        boolean vip = cliente.getTipoAbono() == modelo.TipoAbono.VIP;

        String texto =
            "DATOS PERSONALES\n" +
            "Nombre: " + nombre + "\n" +
            "DNI: " + dni + "\n" +
            "Email: " + email + "\n" +
            (telefono != null ? "Teléfono: " + telefono + "\n" : "") +
            "\nABONO\n" +
            "Tipo: " + abono + "\n" +
            "Descuento: " + descuento + "%\n" +
            "Acceso a sala VIP: " + (vip ? "Sí" : "No") + "\n" +
            "\nREGLAS IMPORTANTES\n" +
            "- Puedes cancelar una reserva hasta 2 horas antes de la sesión.\n";

        jTextArea1.setText(texto);
        jTextArea1.setCaretPosition(0); // para que empiece arriba
    }
    
    private int obtenerDescuentoPorAbono() {
        // porcentajeDescuento viene como 0.10, 0.25, 0.40
        return (int) Math.round(cliente.getTipoAbono().getPorcentajeDescuento() * 100.0);
    }

    private void configurarTablaMisReservas() {
        // Selección por fila completa
        tablaMisReservas.setRowSelectionAllowed(true);
        tablaMisReservas.setColumnSelectionAllowed(false);
        tablaMisReservas.setSelectionMode(
            javax.swing.ListSelectionModel.SINGLE_SELECTION
        );

        // No permitir edición (doble seguridad)
        tablaMisReservas.setDefaultEditor(Object.class, null);

        // No permitir mover columnas
        tablaMisReservas.getTableHeader().setReorderingAllowed(false);
    }

    private void cargarMisReservas() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tablaMisReservas.getModel();

        // Limpiar tabla
        model.setRowCount(0);

        for (modelo.Reserva r : controlador.obtenerReservasCliente(cliente)) {
            modelo.Sesion s = r.getSesion();

            Object[] fila = new Object[] {
                r.getCodigoReserva(),                    // Código Reserva
                s.getCodigoSesion(),                    // Código Sesión
                s.getPelicula().getTitulo(),            // Película
                FMT_FECHA.format(s.getFecha()),                          // Fecha Sesión
                FMT_HORA.format(s.getHoraInicio()),                     // Hora Sesión
                s.getSala().getNumero(),                // Sala
                r.getNumEntradas(),                     // Entradas
                r.getDescripcionExtras(),               // Extras
                String.format("%.2f €", r.getPrecioFinal()), // Precio Final
                r.getEstado()                           // Estado Reserva
            };

            model.addRow(fila);
        }
    }

    private void configurarTablaCartelera() {
        // Selección por fila completa
        jTable1.setRowSelectionAllowed(true);
        jTable1.setColumnSelectionAllowed(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // No editable
        jTable1.setDefaultEditor(Object.class, null);

        // No reordenar columnas
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    private void configurarEventosCartelera() {
        // Cuando seleccionas una sesión -> habilitar botón
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) return;

            int fila = jTable1.getSelectedRow();
            boolean haySeleccion = (fila != -1);

            RealizarReserva.setEnabled(haySeleccion);
            ConfirmarReserva.setEnabled(false);
            PanelReserva.setVisible(false);
            codigoSesionSeleccionada = null;

            if (haySeleccion) {
                codigoSesionSeleccionada = jTable1.getValueAt(fila, 0).toString();
            }
        });

        // Spinner cambia -> recalcular precio
        jSpinner1.addChangeListener(e -> actualizarPrecioEstimado());

        // Checkboxes cambian -> recalcular precio y gestionar exclusividad del combo
        jCheckBox1.addActionListener(e -> {
            if (jCheckBox3.isSelected()) jCheckBox1.setSelected(false);
            actualizarPrecioEstimado();
        });

        jCheckBox2.addActionListener(e -> {
            if (jCheckBox3.isSelected()) jCheckBox2.setSelected(false);
            actualizarPrecioEstimado();
        });

        jCheckBox3.addActionListener(e -> {
            if (jCheckBox3.isSelected()) {
                // si combo, anulamos palomitas/bebida
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
            }
            actualizarPrecioEstimado();
        });
    }

    private boolean sesionEsReservable(modelo.Sesion s) {
        java.time.LocalDateTime inicio = java.time.LocalDateTime.of(s.getFecha(), s.getHoraInicio());
        return inicio.isAfter(java.time.LocalDateTime.now())
               && s.getEstado() == modelo.EstadoSesion.PROGRAMADA
               && s.getPlazasDisponibles() > 0;
    }

    private java.time.LocalDateTime inicioSesion(modelo.Sesion s) {
        return java.time.LocalDateTime.of(s.getFecha(), s.getHoraInicio());
    }

    private java.time.LocalDateTime finSesion(modelo.Sesion s) {
        int durMin = s.getPelicula().getDuracionMinutos();
        return inicioSesion(s).plusMinutes(durMin);
    }

    private boolean sesionHaFinalizado(modelo.Sesion s) {
        // now >= fin
        return !java.time.LocalDateTime.now().isBefore(finSesion(s));
    }

    private boolean sesionEstaEnCurso(modelo.Sesion s) {
        java.time.LocalDateTime now = java.time.LocalDateTime.now();
        java.time.LocalDateTime ini = inicioSesion(s);
        java.time.LocalDateTime fin = finSesion(s);
        return (now.isAfter(ini) || now.isEqual(ini)) && now.isBefore(fin);
    }

    private void cargarCartelera() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String generoStr = (String) jComboBox1.getSelectedItem();
        boolean filtrarPorGenero = !"TODAS".equals(generoStr);
        modelo.Genero genero = filtrarPorGenero ? modelo.Genero.valueOf(generoStr) : null;

        for (modelo.Sesion s : controlador.obtenerSesionesDisponibles()) {
            if (!sesionEsReservable(s)) continue;                 // (ver cambio 2)
            if (filtrarPorGenero && s.getPelicula().getGenero() != genero) continue;

            modelo.Pelicula p = s.getPelicula();

            double precioBase = s.getPrecioBase();
            double recargo = p.getRecargoProyeccion();
            double precioEntrada = s.calcularPrecioEntrada();

            Object[] fila = new Object[] {
                s.getCodigoSesion(),                 // 0 Codigo Sesion
                p.getTitulo(),                       // 1 Pelicula
                p.getGenero(),                       // 2 Genero
                p.getTipoProyeccion(),               // 3 Tipo (si no existe, ver nota abajo)
                FMT_FECHA.format(s.getFecha()),      // 4 Fecha
                FMT_HORA.format(s.getHoraInicio()),  // 5 Hora
                s.getSala().getNumero(),             // 6 Sala
                String.format("%.2f €", precioBase), // 7 Precio Base
                String.format("%.2f €", recargo),    // 8 Recargo
                String.format("%.2f €", precioEntrada), // 9 Precio Final (precio entrada)
                s.getPlazasDisponibles()             // 10 Plazas disponibles
            };

            model.addRow(fila);
        }
    }

    private void actualizarPrecioEstimado() {
        if (codigoSesionSeleccionada == null) {
            PrecioEstimado.setText("");
            return;
        }

        modelo.Sesion sesion = controlador.buscarSesionPorCodigo(codigoSesionSeleccionada);
        if (sesion == null) {
            PrecioEstimado.setText("");
            return;
        }

        int entradas = (int) jSpinner1.getValue();
        double precioEntrada = sesion.calcularPrecioEntrada();
        double subtotalEntradas = precioEntrada * entradas;

        // Descuento por abono (porcentaje)
        double descuento = cliente.getTipoAbono().getPorcentajeDescuento();
        double totalEntradas = subtotalEntradas * (1.0 - descuento);

        // Extras (asumimos combo excluyente)
        double extras = 0.0;
        if (jCheckBox3.isSelected()) {
            extras += 4.0;
        } else {
            if (jCheckBox1.isSelected()) extras += 3.0;
            if (jCheckBox2.isSelected()) extras += 2.0;
        }

        double total = totalEntradas + extras;
        PrecioEstimado.setText(String.format("%.2f €", total));
    }

    private String generarCodigoReserva() {
        java.util.Random rnd = new java.util.Random();
        String codigo;
        do {
            int n = 1000 + rnd.nextInt(9000); // R1000..R9999
            codigo = "R" + n;
        } while (controlador.buscarReservaPorCodigo(codigo) != null);
        return codigo;
    }


    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarReserva;
    private javax.swing.JButton ConfirmarReserva;
    private javax.swing.JPanel PanelReserva;
    private javax.swing.JTextField PrecioEstimado;
    private javax.swing.JButton RealizarReserva;
    private javax.swing.JTextField TextAbono;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tablaMisReservas;
    // End of variables declaration//GEN-END:variables
}
