/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.empleado;

import controlador.ControladorCine;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.LocalTime;
import modelo.Pelicula;
import modelo.Sala;
import excepciones.EntidadNoEncontradaException;
import excepciones.SalaNoCompatibleIMAXException;
import excepciones.SalaOcupadaException;



/**
 *
 * @author Usuario
 */
public class ProgramarSesionDialog extends javax.swing.JDialog {
    
    private final ControladorCine controlador;
    private boolean creada = false;
    private java.util.List<modelo.Sala> todasLasSalas;
    private static final java.time.format.DateTimeFormatter F_ES =
        java.time.format.DateTimeFormatter.ofPattern("dd-MM-uuuu");


    /**
     * Creates new form ProgramarSesionDialog
     */
    public ProgramarSesionDialog(java.awt.Frame parent, boolean modal, ControladorCine controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();

        setTitle("Programar sesión");
        setLocationRelativeTo(parent);

        spnPrecioBase.setModel(new javax.swing.SpinnerNumberModel(8.0, 0.0, 100.0, 0.5));

        // Datos base
        todasLasSalas = controlador.obtenerSalas();

        // Rellenar películas (objetos)
        cargarPeliculasEnCombo();

        // Rellenar salas filtradas según la película seleccionada
        cargarSalasEnComboFiltradas();

        txtFecha.setText(LocalDate.now().format(F_ES));
        txtHora.setText("20:00");
    }

    
    public boolean isCreada() {
        return creada;
    }
    
    private void cargarPeliculasEnCombo() {
        cmbPelicula.removeAllItems();
        for (Pelicula p : controlador.obtenerPeliculas()) {
            cmbPelicula.addItem(p);
        }
    }
    
    private void cargarSalasEnComboFiltradas() {
        cmbSala.removeAllItems();

        modelo.Pelicula peli = (modelo.Pelicula) cmbPelicula.getSelectedItem();
        if (peli == null) return;

        for (modelo.Sala s : todasLasSalas) {
            // Usa la compatibilidad real del modelo (IMAX solo donde toca)
            if (peli.esCompatibleConSala(s)) {
                cmbSala.addItem(s);
            }
        }

        // Si no hay salas compatibles, avisa
        if (cmbSala.getItemCount() == 0) {
            if (lblAvisoCompatibilidad != null) {
                lblAvisoCompatibilidad.setText("No hay salas compatibles con esta película.");
            }
        } else {
            if (lblAvisoCompatibilidad != null) {
                lblAvisoCompatibilidad.setText(""); // limpia aviso
            }
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoSesion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbPelicula = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbSala = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        spnPrecioBase = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblAvisoCompatibilidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Película");

        cmbPelicula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPelicula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeliculaItemStateChanged(evt);
            }
        });

        jLabel3.setText("Fecha (DD-MM-AAAA)");

        jLabel4.setText("Hora (HH:MM)");

        jLabel5.setText("Sala");

        cmbSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Precio base");

        jLabel7.setText("- IMAX solo para Sala 1");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cmbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear)
                                .addGap(40, 40, 40)
                                .addComponent(btnCancelar))
                            .addComponent(spnPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAvisoCompatibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnCancelar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAvisoCompatibilidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String codigoSesion = txtCodigoSesion.getText().trim();
        Pelicula peli = (Pelicula) cmbPelicula.getSelectedItem();
        Sala sala = (Sala) cmbSala.getSelectedItem();

        if (codigoSesion.isEmpty() || peli == null || sala == null) {
            JOptionPane.showMessageDialog(this, "Rellena código, película y sala.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalDate fecha;
        LocalTime hora;
        try {
            fecha = LocalDate.parse(txtFecha.getText().trim(), F_ES);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Fecha inválida. Usa formato DD-MM-AAAA.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            hora = LocalTime.parse(txtHora.getText().trim()); // HH:MM
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Hora inválida. Usa formato HH:MM.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double precioBase = ((Number) spnPrecioBase.getValue()).doubleValue();

        try {
            controlador.programarSesion(
                    codigoSesion,
                    peli.getCodigo(),
                    fecha,
                    hora,
                    sala.getNumero(),
                    precioBase
            );

            creada = true;
            JOptionPane.showMessageDialog(this, "Sesión programada correctamente.");
            dispose();

        } catch (SalaNoCompatibleIMAXException ex) {
            JOptionPane.showMessageDialog(this, "Esa película no es compatible con la sala seleccionada (IMAX).", "Error", JOptionPane.ERROR_MESSAGE);

        } catch (SalaOcupadaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Sala ocupada", JOptionPane.ERROR_MESSAGE);

        } catch (EntidadNoEncontradaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "No encontrado", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cmbPeliculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeliculaItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            cargarSalasEnComboFiltradas();
        }
    }//GEN-LAST:event_cmbPeliculaItemStateChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox cmbPelicula;
    private javax.swing.JComboBox cmbSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAvisoCompatibilidad;
    private javax.swing.JSpinner spnPrecioBase;
    private javax.swing.JTextField txtCodigoSesion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
